:PROPERTIES:
:ID:       eb8bcc8b-f176-49cc-9cb9-f08ea26bdd3f
:END:
#+title: Recursion

* TOC :TOC_2:

* Overview
A recursive function typically contains a conditional expression which has three parts:
1. A true-or-false-test that determines whether the function is called again, here called the *do-again-test*.
2. Call again
3. An expression that returns a different value each time the function is called, here called the *next-step-expression*.

* Common Patterns
** Simple Pattern
#+begin_src elisp
(defun name-of-recursive-function (argument-list)
  "documentation…"
  (if do-again-test
    body…
    (name-of-recursive-function
         next-step-expression)))
#+end_src
- Examples
#+begin_src elisp
(setq animals '(gazelle giraffe lion tiger))

(defun print-elements-recursively (list)
  "Print each element of LIST on a line of its own.
Uses recursion."
  (when list                            ; do-again-test
        (print (car list))              ; body
        (print-elements-recursively     ; recursive call
         (cdr list))))                  ; next-step-expression

(print-elements-recursively animals)

;; example 2
(defun triangle-recursively (number)
  "Return the sum of the numbers 1 through NUMBER inclusive.
Uses recursion."
  (if (= number 1)                    ; do-again-test
      1                               ; then-part
    (+ number                         ; else-part
       (triangle-recursively          ; recursive call
        (1- number)))))               ; next-step-expression

(triangle-recursively 7)
#+end_src

** using ~cond~
#+begin_src elisp
(defun triangle-using-cond (number)
  (cond ((<= number 0) 0)
        ((= number 1) 1)
        ((> number 1)
         (+ number (triangle-using-cond (1- number))))))
#+end_src

** every
- If a list be empty, return nil.
- Else, act on the beginning of the list (the CAR of the list)
  - through a recursive call by the function on the rest (the CDR) of the list
  - and, optionally, combine the acted-on element, using cons, with the results of acting on the rest.
#+begin_src elisp
(defun print-elements-recursively (list)
  "Print each element of LIST on a line of its own.
Uses recursion."
  (when list                            ; do-again-test
        (print (car list))              ; body
        (print-elements-recursively     ; recursive call
         (cdr list))))                  ; next-step-expression

(print-elements-recursively animals)
#+end_src
- When the list is empty, do nothing.
- But when the list has at least one element,
  - act on the beginning of the list (the CAR of the list),
  - and make a recursive call on the rest (the CDR) of the list.

** accumulate
- If a list be empty, return zero or some other constant.
- Else, act on the beginning of the list (the CAR of the list),
  - and combine that acted-on element, using + or some other combining function, with
  - a recursive call by the function on the rest (the CDR) of the list.
#+begin_src elisp
(defun add-elements (numbers-list)
  "Add the elements of NUMBERS-LIST together."
  (if (not numbers-list)
      0
    (+ (car numbers-list) (add-elements (cdr numbers-list)))))

(add-elements '(1 2 3 4)) ; => 10
#+end_src

** keep
Again, this is very like the every pattern, except the element is skipped unless it meets a criterion.
#+begin_src elisp
(defun keep-three-letter-words (word-list)
  "Keep three letter words in WORD-LIST."
  (cond
   ;; First do-again-test: stop-condition
   ((not word-list) nil)

   ;; Second do-again-test: when to act
   ((eq 3 (length (symbol-name (car word-list))))
    ;; combine acted-on element with recursive call on shorter list
    (cons (car word-list) (keep-three-letter-words (cdr word-list))))

   ;; Third do-again-test: when to skip element;
   ;;   recursively call shorter list with next-step expression
   (t (keep-three-letter-words (cdr word-list)))))

(keep-three-letter-words '(one two three four five six)) ; (one two six)
#+end_src
* Tail Recursive
It involves writing two function definitions, an *initialization function* and a *helper function*.
- The initialization function sets up the job
- The helper function does the work

** Recursion with Deferments
#+begin_src elisp
(defun factorial (n)
  (if (<= n 1)
      1
    (* n (factorial (1- n)))))
#+end_src
#+begin_example

arg 7 => (* 7 (factorial 6)) # defered
arg 6 => (* 7 6 (factorial 5)) # defered
...
arg 1 => (* 7 6 5 4 3 2 1)

#+end_example
This design for the function defers the calculation of the factorial of N until the factorial of N-1 is known.

** No Deferment
#+begin_src elisp
;; tail-recursive factorial
(defun factorial (n) ; initialization
  "Calculate the factorial of N using a tail-recursive helper."
  (factorial-helper n 1))

(defun factorial-helper (n acc) ; helper
  "Tail-recursive helper function for factorial calculation."
  (if (<= n 1)
      acc
    (factorial-helper (1- n) (* n acc))))
#+end_src

#+begin_example
arg 7 1 => 6 7
arg 6 7 => 5 42
...
arg 1 5040 => 5040
#+end_example
