:PROPERTIES:
:ID:       95582cbe-1989-4662-b5d3-a9c9fccefb6f
:END:
#+title: Anki Tips
#+filetags: :Hacks:Learning:

* Effective Learning
- Keep it simple :: The shorter your cards, the easier they are to review.
- Don't memorize without understanding :: The best way to learn languages is in context, which means seeing those words used in a sentence.

** [[https://super-memory.com/articles/20rules.htm][Effective Learning 20 Rules]]
- Rule 4: *Minimum information principle*
  - The easier you make it to answer a question in Anki, the less likely you are to remember that question when you encounter it in real life.

* Cloze Deletion
- Why to use cloze deletion :: Rule 5
- ~{{c1::Canberra::city}} was founded in 1913.~
  - Anki will treat the text after the two colons as a hint
  - =[city] was founded in 1913.=

* Field Replacements
| Prefix                | Description              |
|-----------------------+--------------------------|
| hint                  | For hint fields          |
| text                  | HTML format stripping    |
| furigana, kana, hanji | Ruby charaters           |
| type                  | Type for answer checking |

** Special Fields
Tags, Type(Note type), Deck, Subdeck, CardFlag, Card(Card type), FrontSide

** Hidden Fields (Hint Fields)
1. Add a field to store the hint in
2. Add ~{{hint:MyField}}~ to template (If MyField is empty, nothing will be shown.)

** Linking to Online Dictionary
~<a href="http://example.com/search?q={{text:Front}}">check in dictionary</a>~
- If you prefix a field name with ~text:~, Anki will not include any html formatting.

** Ruby Characters
Some languages commonly use *annotations above the text* to display the pronunciation of characters.
- In field edit: ~Text[Ruby]~, ~日本語[にほんご]~, ~世[よ]の 中[なか]~
- Templates:
  - ~{{furigana:MyField}}~: Show both kanji and kana
  - ~{{kana:MyField}}~ or ~{{hanji:MyField}}~

** Typing Fields
- ~{{type:Text}}~
- ~{{cloze:Text}}~
- ~{{type:cloze:Text}}~

** Conditional Replacement
#+begin_example
This text is always shown.

{{#FieldName}}
    This text is only shown if FieldName has text in it
{{/FieldName}}

{{^FieldName}}
    This text is only shown if FieldName is empty
{{/FieldName}}
#+end_example
- A real life example: showing a label if the field is not empty
#+begin_example
{{#Tags}}
    Tags: {{Tags}}
{{/Tags}}
#+end_example

* Styling
#+begin_src css
.card {
    font-family: arial;
    font-size: 20px;
    text-align: center;
    color: black;
    background-color: white;
}
#+end_src
- [[https://docs.ankiweb.net/templates/styling.html#installing-fonts][Installing Fonts]]

** Image Resizing
#+begin_src css
img {
    max-width: none;
    max-height: none;
}
#+end_src

** Field Styling
- Wrap the field: ~<div class=mystyle1>What is {{MyField}}?</div>~
- Add style
#+begin_src css
.mystyle1 {
    font-family: ayuthaya;
    font-size: 30px;
}
#+end_src

** Night Mode
#+begin_src css
.card.nightMode {
    background-color: #555;
}
.nightMode .myclass {
    color: yellow;
}
#+end_src

** Audio Replay Buttons
#+begin_src css
.replay-button svg {
  width: 20px;
  height: 20px;
}
.replay-button svg circle {
  fill: blue;
}
.replay-button svg path {
  stroke: white;
  fill: green;
}
#+end_src

** Platform-Specific CSS
#+begin_src css
/* Windows */
.win .myclass {
  font-family: "Example1";
}
/* macOS */
.mac .myclass {
  font-family: "Example2";
}
/* Linux desktops */
.linux:not(.android) .myclass {
  font-family: "Example3";
}
/* both Linux desktops, and Android devices */
.linux .myclass {
  font-family: "Example4";
}
/* both Android and iOS */
.mobile .myclass {
  font-family: "Example5";
}
/* iOS */
.iphone .myclass,
.ipad .myclass {
  font-family: "Example6";
}
/* Android */
.android .myclass {
  font-family: "Example7";
}
#+end_src

* Add-ons Recommendations
- Advanced Review Bottom Bar: 1136455830
- Review Heatmap: 1771074083
- Anki Connect: 2055492159
- AwesomeTTS: 1436550454
- Aglish: 38866997
- Bulk Image Downloader: 8280891

** AnkiBrain
1. 1915225457
2. Local Mode
3. =/.local/share/Anki2/addons21/1915225457/=
4. ~uv python pin 3.9.13~
5. ~uv venv -p 3.9.13~
6. ~sudo pacman -S openmp~ or ~libomp-dev~ on Ubuntu
7. ~uv pip install -r linux_requirements.txt~
