:PROPERTIES:
:ID:       5a856fd8-e1ec-4964-8862-17e7d48f906c
:END:
#+title: C++ Concurrency
#+filetags: C++

* Purpose
Two main reasons:

- Separation of concerns
  - Based on the conceptual design rather than an attempt to increase throughput
  - The number of threads is *independent* of the number of CPU cores available.

- Performance
  - Task parallelism: Divide a single task into parts and run each in parallel.
  - Data parallelism: Each thread performs the same operation on different parts of the data.

* Lock-based
** [[id:7f6ffc9c-dc1c-410c-b81e-36e8fdff065e][Race Condition]]

** Promises and Futures
:PROPERTIES:
:ID:       b07d9886-dc9c-47f2-916e-536e16bde143
:END:
The mechanism acts as a single-use channel between the threads.
The sending end of the channel is called *"promise"* while the receiving end is called *"future"*.

*** Promises
The class template ~std::promise~ provides a convenient way to store a value or an exception that will acquired asynchronously at a later time via a ~std::future~ object. Each ~std::promise~ object is meant to be used *only a single time*.

Promises *can not be copied*, because the promise-future concept is a two-point communication channel for one-time use. *Therefore, we must pass the promise to the thread function using ~std::move~.*

*** Futures
- [[id:affca3ee-0c2d-4a19-a268-e1ab078e9117][STL Futures]]
- get future object by calling ~promise.get_future()~
- use ~future.get()~ to receive data from child thread
  - This method will block until data is available
  - If the result is movable, it will be moved. Otherwise it will be copied instead.
- After ~future.get()~ has been called once, the future is *no longer usable*. (data in future is moved)
- Futures also provide ~wait()~ and ~wait_for(timeout)~ methods.

#+begin_src c++
auto status = ftr.wait_for(std::chrono::milliseconds(1000));
if (status == std::future_status::ready) {
  std::cout << "Result = " << ftr.get() << std::endl;
} else if (status == std::future_status::timeout || status == std::future_status::deferred) {
  std::cout << "Result unavailable" << std::endl;
}
#+end_src
*** Drawbacks
1. Information can only be passed from the worker thread to the parent.
2. Promises and future are meant for one-time use only.

*** Examples
#+begin_src c++
// promise can not be copied
void divideByNumber(std::promise<double> &&prms, double num, double denom) {
    std::this_thread::sleep_for(std::chrono::milliseconds(500)); // simulate work
    try {
        if (denom == 0)
            throw std::runtime_error("Exception from thread: Division by zero!");
        else
            prms.set_value(num / denom);
    }
    catch (...) {
        prms.set_exception(std::current_exception());
    }
}

int main() {
    // create promise and future
    std::promise<double> prms;
    std::future<double> ftr = prms.get_future();

    // start thread and pass promise as argument
    double num = 42.0, denom = 0.0;
    std::thread t(divideByNumber, std::move(prms), num, denom);

    // retrieve result within try-catch-block
    try {
        double result = ftr.get();
        std::cout << "Result = " << result << std::endl;
    }
    catch (std::runtime_error e) {
        std::cout << e.what() << std::endl;
    }

    // thread barrier
    t.join();

    return 0;
}

#+end_src

*** Alternative Simple [[id:fb10c09a-372d-4137-ad09-0a535508822f][~std::async~]]

** Task-based Concurrency
The use of ~std::async~ (and thus *tasks*) take the burden of this decision away from the user and let the system decide whether to execute the code sequentially or as a thread.
- With tasks, the system takes care of many details (e.g. join). With threads, the programmer is responsible for many details.
- Threads and tasks are used for different problems.
  - Threads have more to do with *latency*. When you have functions that can block (e.g. file input, server connection), threads can avoid the program to be blocked
  - Tasks on the other hand focus on *throughput*, where many operations are executed in parallel.

** [[id:d0df6e46-ba6c-4edc-9105-01a8d7692d68][Mutex]]
** [[id:bd28f916-60e2-481f-b536-112e0181a1da][Locks]]
** [[id:890f2b58-21c3-48b7-a975-c532eedc01ec][Condition Variables]]
** [[id:7475eede-346a-403e-9aac-91cab1e71a1f][Deadlock Issue]]

* Lock-free
** [[id:c47f4f7a-d15b-4c9a-8ccb-d00d473059cd][Memory Model]]
** [[id:9fb084bb-ba72-4136-8e91-60f0b7ba216f][Atomics]]

* Lock-based Data Structure
- [[id:f8a4353c-d3ec-4439-824a-23c454a71a31][Designing Thread-safe Data Structures]]
- [[id:4f91a36d-4b44-4393-8dda-2e89455d348e][Thread-safe Stack]]
- [[id:7f7c8750-1a2d-4a09-b008-e999dd17784d][Thread-safe Queue]]
- [[id:3b561763-85db-44bd-8b50-236e935dd169][Thread-safe Lookup Table]]
- [[id:4756b244-4ab3-4e55-ba64-4dd25ae847f0][Thread-safe List]]

* Lock-free Data Structures
- [[id:2569c73d-2087-4aad-89db-809f0ac3619a][Designing Lock-free Data Structures]]
- [[id:277f745a-2767-4327-95b8-26a69a9d1cc1][Lock-free Stack]]

* Examples
** [[id:f31b1ca4-bcd9-466a-af90-1484e8b28684][Parallel Computation]]
** [[id:0874134e-082a-4f60-8c94-cc0ed6e4001b][Thread-safe Lazy Initialization]]
* [[id:bfb36506-4b84-4171-b209-b7b155bf75fb][STL Concurrency]]
