:PROPERTIES:
:ID:       df7a26d0-d2d8-4cd0-9219-2b2e13e19816
:END:
#+title: nftables
#+filetags: :Network:

- links :: [[id:cee785fb-8f4b-4230-ad02-312714729965][~iptables~]]

* Basic Operations
** Tables
- Tables are the top-level containers within an nftables ruleset;
  - They hold chains, sets, maps, flowtables, and stateful objects.
- Each table belongs to exactly one *family*

*** Family
- ip: Tables of this family see IPv4 traffic.
- ip6: Tables of this family see IPv6 traffic.
- inet: Tables of this family see both IPv4 and IPv6 traffic.
- arp: Tables of this family see ARP-level(L2) traffic, before any L3 handling is done by the kernel.
- bridge: Tables of this family see traffic/packets traversing bridges.
- netdev: The netdev family is different from the others in that it is used to create base chains attached to a single network interface.

*** Examples
#+begin_src bash
nft list tables
nft add table ip foo # adding
nft delete table ip foo # deleting
nft flush table ip foo # flushing (delete all the rules)
#+end_src

** Chains
- With nftables you attach your rules to chains
  - Create a base chain with name
  - Base chains are those that are registered into the *Netfilter hooks*
- Syntax :: ~nft add chain [<family>] <table_name> <chain_name> { type <type> hook <hook> priority <value> \; [policy <policy> \;] [comment \"text comment\" \;] }~
  - If you are running these commands from a shell such as bash, all the special characters need to be escaped.
  - Or, just quote everything within single quotes.

*** Chain Types
- filter :: which is used to filter packets. This is supported by the arp, bridge, ip, ip6 and inet table families.
- route :: which iused to reroute packets if any relevant IP header field or the packet mark is modified. This is supported by the ip, ip6 and inet table families.
- nat :: which is used to perform Networking Address Translation (NAT). The nat chain type is supported by the ip, ip6 and inet table families.

*** Base Chain Hooks
- ingress :: sees packets immediately after they are passed up from the NIC driver, before even prerouting.
- prerouting :: sees all incoming packets, before any routing decision has been made.
- input :: sees incoming packets that are addressed to and have now been routed to the local system and processes running there.
- forward :: sees incoming packets that are not addressed to the local system.
- output :: sees packets that originated from processes in the local machine.
- postrouting :: sees all packets after routing, just before they leave the local system.

*** Base Chain Examples
#+begin_src bash
# Filter incoming packets(directed to local processes)
# Add a new chain input to the foo table
# 1. The chain attached to the input hook so it will see packets that are addressed to the local processes.
# 2. Priority determines which chain sees packets before another.
# ip: family, foo: table bame, input, chain name
nft add chain ip foo input '{ type filter hook input priority 0 ; }'

# Filter outgoing packets(generated by local processes)
# Used for A computer which does not forward traffic, you can also register the output chain.
nft add chain ip foo output '{ type filter hook output priority 0 ; }'

# Specify the default policy
# The two possible default policies are accept and drop.
nft add chain ip foo output '{ type filter hook output priority 0 ; policy accept; }'


# When adding a chain on ingress hook, it is mandatory to specify the device where the chain will be attached.
nft add chain netdev foo dev0filter '{ type filter hook ingress device eth0 priority 0 ; }'


# Run nft in interactive mode.
# Create regular chain - regular chain is analogous to iptables user-defined chains
nft -i
> add chain [family] <table_name> <chain_name> [{ [policy <policy> ;] [comment "text comment about this chain" ;] }]

# Deleting chains
nft delete chain [family] <table_name> <chain_name>

# Flushing chains
nft flush chain <table_name> <chain_name>
#+end_src

*** Simple Configuration for Standalone PC
#+begin_src bash
nft add table ip filter
nft add chain ip filter input '{ type filter hook input priority 0 ; }'
nft add chain ip filter output '{ type filter hook output priority 0 ; }'
#+end_src

** Rules
Rules take action on network packets based on whether they match specified criteria.

*** Examples
#+begin_src bash
# Listing rules
nft list table <family> <table_name>
# list by chain
nft list chain <family> <table_name> <chain_name>

# Appending new rules
# filter is the table and output is the chain
nft add rule <family> <table_name> <chain_name> ip daddr 8.8.8.8 counter
# The example above adds a rule to match all packets seen by the output chain whose destination is 8.8.8.8
# The counter(optional) is used to track the number of packets and bytes that match the rule.

# Testing
ping -c 1 8.8.8.8
nft -nn list <family> <table_name> # for fully numerical output

# Getting handle number
nft -a list <family> <table_name>

# Inserting rules before the rule with handle 8
nft insert rule <family> <table_name> <chain_name> position 8 ip daddr 127.0.0.8 drop
#+end_src

# Removing rules
nft delete rule <family> <table_name> <chain_name> handle 5

# Removing all in a chain
nft flush chain <family> <table_name> <chain_name>
# REmoving all in a table
nft flush <family> <table_name> filter


# Replacing rules
# Specify its handle number and the new rule that you want to replace it
nft replace rule filter input handle 2 counter

* Matching
- [[https://wiki.nftables.org/wiki-nftables/index.php/Matching_packet_metainformation][Metainformation]]
- [[https://wiki.nftables.org/wiki-nftables/index.php/Matching_packet_headers][Packet Headers]]
- [[https://wiki.nftables.org/wiki-nftables/index.php/Matching_connection_tracking_stateful_metainformation][Connection tracking stateful metainformation]]
- [[https://wiki.nftables.org/wiki-nftables/index.php/Matching_routing_information][Routing information]]
- [[https://wiki.nftables.org/wiki-nftables/index.php/Rate_limiting_matchings][Rate limiting matchings]]

* Acting on Matches
- accept, drop, reject, counter
  - ~reject~ e.g.: ~nft add rule ip6 filter input reject with icmpv6 type no-route~

** Jumping to Chain
To structure your ruleset using a tree of chains.
#+begin_src bash
# First create at least one regular chain
nft add chain ip filter tcp-chain

# tcp traffic jump to tcp-chain and packet will return to the chain of the calling rule after the end.
nft add rule ip filter input ip protocol tcp jump tcp-chain

# add a simple rule to that tcp-chain to count packets and bytes
nft add rule ip filter tcp-chain counter
#+end_src

** Logging Traffics
- ~nft add rule filter input iif lo log tcp dport 22 accept~
  - will log all packets coming on lo interface and not only the ones with destination port 22.
