:PROPERTIES:
:ID:       9dada7ef-84e8-44f7-b068-4837411eda69
:END:
#+title: Smart Pointers
#+filetags: C++

* Overview
Smart pointers ensure that programs are free of memory leaks while also remaining exception-safe.

* Raw Pointers
In modern C++, raw pointers managed with ~new~ and ~delete~ should only be used *in small blocks of code with limited scope*, where *performance is critical* and *ownership rights of the memory resource are clear*.

** Some Rules of Using Raw Pointer
- A call to ~new~ should not be located too far away from the corresponding ~delete~.
- Calls to ~new~ and ~delete~ should always be hidden from third parties.

* Unique Pointers
~std::unique_ptr~ is a smart pointer which *exclusively owns* a dynamically allocated resource on the heap.

** When to Use?
Unique pointers are useful when working with *a temporary heap resource* that is no longer needed once it goes out of scope.

Unique pointers should be the *default choice* unless you know for certain that sharing is required at a later stage.

A *key feature* of a unique pointer, which makes it so well-suited as a *return type for many functions*, *is the possibility to convert it to a shared pointer*.

** Transferring Ownership
#+begin_src c++
auto src_ptr = std::make_unique<MyObject>();
auto dest_ptr = std::move(src_ptr);
#+end_src

* Shared Pointers
~std::shared_ptr~ points to a heap resource but does not explicitly own it.

** When to Use?
This smart pointer type is useful for cases where you require access to a memory location on the heap in multiple parts of your program and you want to make sure that whoever owns a shared pointer to the memory can rely on the fact that it will be accessible throughout the lifetime of that pointer.

** Use ~reset()~ to Redirect
~reset()~ will destruct the previous internal resource(~delete~ obj), then ~new~ with a new resource.

** Use ~make_shared~
The use of ~std::make_shared~ to avoid the overhead of a second memory allocation for the reference count

In C++, when you create a shared pointer using ~std::shared_ptr~, the memory for the object and the reference count is allocated separately.

~std::make_shared~ allocates memory for both the object and the reference count in a single memory block.
** Pitfalls
- May produce *circular references*. Use ~std::weak_ptr~ to avoid it.
- When using raw pointers retrieved from the ~get()~ function, you should take special care not to delete them or to create new smart pointers from them.

* Weak Pointers
~~std::weak_ptr~ behaves similar to the shared pointer but does not increase the reference counter. There can be multiple weak pointers to the same resource.

Weak pointers hold a *non-owning reference* to an object that is *managed by another shared pointer*.

*The important rule*: You can only create weak pointers out of shared pointers or out of another weak pointer.

** Compare with Raw Pointer
We can check the validity of its resource with ~expired()~ function.

* Converting Between Smart Pointers
- unique to shared: ~std::move~
- weak to shared: ~weak_ptr.lock()~
- shared to raw: ~shared_ptr.get()~

* Passing Smart Pointers
** Passing to Functions
- A function that does not manipulate the lifetime or ownership should use *raw pointers or references* instead.
- A function should take smart pointers as parameter only if it *examines or manipulates the smart pointer itself*.

** Pass-by-value
Pass-by-value is used to *lend the ownership* of smart pointers.

** Pass-by-reference
*** ~unique_ptr~
We pass a non-const reference to a ~unique_ptr~ to a function if it might modify it in any way, including deletion and reassignment to a different resource.

Passing a ~unique_ptr~ as ~const~ is not useful as the function will not be able to do anything with it.

*** ~shared_ptr~
A ~shared_ptr~ can either be passed as const or non-const reference.

The ~const~ should be used when you want to express that the function will only read from the pointer or it might create a local copy and share ownership.

* Returning Smart Pointers
Return a smart pointer, both unique or shared, if the caller needs to manipulate or access the pointer properties. In case the caller just needs the underlying object, a raw pointer should be returned.

Smart pointers should always be returned by value. This is not only simpler but also has the following advantages:
1. The overhead is small due to the move semantics of smart pointers.
2. Compiler uses *Return Value Optimization* (ROV)
3. When returning a *shared_ptr* by value, the internal reference counter is guaranteed to be properly incremented.

* Core Guidelines
- [[https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r-resource-management][Resource Management]]
- [[http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#rsmart-smart-pointers][Smart Pointers]]

** Some Rules
- Use ~unique_ptr~ or ~shared_ptr~ to represent ownership
- Prefer ~unique_ptr~ over ~shared_ptr~ unless you need to share ownership
- Use ~weak_ptr~ to break cycles of ~shared_ptr~
