:PROPERTIES:
:ID:       2569c73d-2087-4aad-89db-809f0ac3619a
:END:
#+title: Designing Lock-free Data Structures
#+filetags: C++


* non-blocking
- blocking
  - Algorithms that use mutexes, condition variables, and futures to synchronize the data are called *blocking* algorithms
  - Library functions that will suspend the execution of a thread until another thread performs an action, are called *blocking* calls.
    - Typically, the OS will suspend a blocked thread completely
- nonblocking: algorithms that *don't use blocking library functions*
  - [[id:247aac50-7fb9-4e63-ba23-cd1a025d5008][Example: Spin-Lock]]: it's *non-blocking* but it's not *lock-free*

* Specific Terms
- Lock-Free :: If multiple threads are operating on a data structure, then after a
bounded number of steps one of them will complete its operation.
- Wait-Free :: Every thread operating on a data structure will complete its operation in a *bounded* number of steps, even if other threads are also operating on
the data structure.

* Lock-free Data Structures
- More than one thread must be able to access the data structure concurrently.
- If one thread accessing is suspended by the scheduler midway through its operation, the others must still be able to complete their operations without waiting for the suspended thread.
- Algorithms use *compare/exchange* operations
  - The reason for using a *compare/exchange* operation is that *another thread might have modified the data in the mean time*. The code need to *redo part* before trying the *compare/exchange* again.
  - This code can still be lock-free if the compare/exchange would eventually succeed *if the other threads were suspended*.
- Lock-free algorithms with *compare/exchange* loops can result in one thread being subject to /starvation/.
  - If one thread doesn't have to continually *retry* its operation, the data structure is *wait-free*.

* Wait-free Data Structures
A wait-free data structure is a lock-free data structure with the additional property that every thread accessing the data structure can complete its operation within a bounded number of steps, regardless of the behavior of other threads.

Algorithms that can involve *an unbounded number of retries* because of clashes with other threads are not *wait-free*.

- *compare/exchange* operations have a loop with no upper bound on the number of times. They are not *wait-free*
- Writing wait-free data structures correctly is *extremely hard*.
  - need to make sure that the steps performed by one thread don't cause an operation on another thread to fail.
  - need some pretty good reasons to write one (when the benefit outweighs the cost of complexity)

* Pros & Cons of Lock-free
** Pros
- Maximum concurrency
  - Preventing concurrency through mutual exclusion is the entire purpose of a mutex lock
  - With a lock-free data structure, some thread makes progress with every step.
  - With a wait-free data structure, every thread can make forward progress.
- Robustness: If a thread dies while holding a lock, that data structure is broken
- Deadlocks are impossible

** Cons
- Complexity over locks
  - ensure that the invariants are upheld
  - pay attention to ordering constraints
- It may *decrease* overall performance
  - atomic operations can be much slower than non-atomic operations (not using cache)
  - always check the performance (worst-case wait time, average wait time. overall execution time)

* Examples
- [[id:b5341053-2f9b-45d3-afa3-3384e75cbd8e][Atomic List]]
- [[id:02247881-b505-4201-83b6-7fdf3903ddd0][Atomic Queue]]
- [[id:277f745a-2767-4327-95b8-26a69a9d1cc1][Lock-free Stack]]
