:PROPERTIES:
:ID:       8ff66d66-2df2-4dad-b09a-9ba4e42736d9
:END:
#+title: Linear Algebra
#+filetags: :LinearAlgebra:Math:

* Concepts
:PROPERTIES:
:ID:       fb5f5003-ae0b-4241-a17d-2dd827c6a320
:ROAM_ALIASES: "Linear Algebra Concepts"
:END:
  - Linear Combinations :: $a\bm{v}+b\bm{w}$ is the linear combination of $\bm{v}$ and $\bm{w}$, $a$ and $b$ are scalars.
  - Span :: The "span" of $\bm{v}$ and $\bm{w}$ is the set of *all* their linear combinations.
  - Linearly Dependent :: one of the vectors can be expressed as a linear combination of the others since it's already in the span of the others. i.e. $\exists{a}\exists{b} | \bm{u} = a\bm{v} + b\bm{w}$
  - Linearly Independent :: $\forall{a}\forall{b} | \bm{u}\ne a\bm{v}+b\bm{w}$
    - Definitions treats all vectors equally: $a\bm{v}+b\bm{w}+c\bm{u}=\bm{0}$ if the only solution is $a=b=c=0$
  - Basis :: The *basis* of a vector space is a set of *linearly independent* vectors that *span* the full space.
  - Rank :: The number of dimensions in the output of a linear transformation. i.e. in the column space.
  - Column Space :: "Column Space" of $A$ is the set of all possible outputs $A\bm{v}$
  - Null Space / Kernel :: The set of vectors that lands on *the origin* in a linear transformation is called the "null space" or the "kernel".
  - Eigenvectors :: Eigenvector is a vector that changes *at most* by a *scalar* factor when that linear transformation is applied to it.
  - Eigenvalues :: Eigenvalue is the factor by which the eigenvector is scaled, denoted by $\lambda$

* [[id:f8567531-6fee-42d1-a78b-c085a3ff4978][Vector]]
* [[id:e38dcf6b-8443-4706-ad9d-01376d79379d][Matrix]]
* [[id:e6dd9e1a-e20b-4bdc-98e7-49565d33db98][Cross Product]]
* Linear Transformation
:PROPERTIES:
:ID:       5721397f-c77b-4e86-936c-1dd5e65133fb
:END:
- Any linear transformation $f$ that maps n-dimensional vectors to m-dimensional vectors can be represented as an $\bm{m\times n}$ matrix.

** Composing Linear Transformation
#+begin_src python
  P_squeezed_then_sheared = F_shear.dot(F_squeeze.dot(P))
  P_squeezed_then_sheared = (F_shear.dot(F_squeeze)).dot(P) # associative

  # Perform dot product on transformation matrices first
  # lead to a very significant performance boost.
  F_squeeze_then_shear = F_shear.dot(F_squeeze)
  P_squeezed_then_sheared = F_squeeze_then_shear.dot(P)
#+end_src

*** Inverse
- $(Q\cdot R)^{-1}=R^{-1}\cdot Q^{-1}$
#+begin_src python
  LA.inv(F_shear.dot(F_squeeze)) == LA.inv(F_squeeze).dot(LA.inv(F_shear)) # reversed order
#+end_src

*** Singular Value Decomposition
It turns out that any $m\times n$ matrix M can be decomposed into the dot product of three simple matrices:
- a rotation matrix $U$ (an $m\times n$ orthogonal matrix)
- a scaling & projecting matrix $\Sigma$ (an $m\times n$ diagonal matrix)
- and another rotation matrix $V^T$ (an $n\times n$ orthogonal matrix)
#+begin_src python
  U, Σ_diag, V_T = LA.svd(F_shear)
  # S_diag is just a 1D array containing the diagonal values of Σ
  Σ = np.diag(S_diag) # now Σ is m x n diagonal matrix
  assert F_shear == U.dot(np.diag(S_diag)).dot(V_T)
#+end_src


* Basis Transformation
:PROPERTIES:
:ID:       5c7bcdaf-de3b-47e5-9096-454320881693
:END:

- $B$ is the new basis written in old basis language.
- $B^{-1}$ is the old basis written in new basis language.

\[B\cdot\begin{bmatrix} x_{new} \\ y_{new} \end{bmatrix}=\begin{bmatrix} x_{old} \\ y_{old} \end{bmatrix}\]

\[B^{-1}\cdot \begin{bmatrix} x_{old} \\ y_{old} \end{bmatrix}=\begin{bmatrix} x_{new} \\ y_{new} \end{bmatrix}\]

** [[id:a20a85ad-d459-477f-bbcc-1df064e9720c][Eigenvectors]]
** [[id:500581c8-ecbd-4fcb-b503-f2f405e6b262][Orthonormal Basis]]

* TODO
- [[id:661e1889-ce72-4cbe-a0ca-7a88944a72e5][The Jacobian]]
- [[id:87392b85-d13e-4923-ab0f-938e1c50a18f][The Hessian]]
