:PROPERTIES:
:ID:       09ea9033-4067-4a2f-b442-b7da136fa5be
:END:
#+title: Financial Terminology
#+filetags: :Quant:Trading:

- Stock :: An asset that represents ownership in a company. A claim on part of a corportation's
  assets and earnings. There are two main types, common and preferred.
- Share :: A single share represents partial ownership of a company relative to the total number
  of shares in existence.
- Common Stock :: One main type of stock; entitles the owner to receive dividends and to vote at
  shareholder meetings.
- Preferred Stock :: The other main type of stock; generally does not entail voting rights, but
  entitles the owner to a higher claim on the assets and earnings of a company.
- Dividend :: A partial distribution of a company's profits to shareholders.
- Capital Gains :: Profits that result from the sale of an asset at a price higher than the
  purchase price.
- Security :: A tradable financial asset.
- Debt Security :: Money that is owed and must be repaid, like government or corporate bonds,
  or certificates of deposit. Also called fixed-income securities.
- Derivative Security :: A financial instrument whereby its value is derived from other assets.
- Equity :: The value of an owned asset minus the amount of all debts on that asset.
- Equity Security :: A security that represents fractional ownership in an entity, such as stock.
- Option Contract :: A contract which gives the buyer the right, but not the obligation, to buy
  or sell an underlying asset at a specified price on or by a specified date
- Futures Contract :: A contract that obligates the buyer to buy or the seller to sell an asset
  at a predetermined price at a specified time in the future
- American Depository Receipts(ADR) :: Foreign stocks are sometimes allowed to trade on a local
  stock exchange via an indirect method such as American Depository Receipts (ADR).
  These are instruments that represent the original stock in a different market.
