:PROPERTIES:
:ID:       5d671286-647d-4870-90d9-fe6553a36af8
:END:
#+TITLE: CPU Usage
- tags :: [[id:76560a4a-b518-478a-8cd2-64473fd2c3aa][Performance Measure]], [[id:60cfb15c-18c7-479a-b489-b14ce161f4bf][Process]], [[id:d3bd3cd6-c056-4093-8abd-b682fecafebd][CPU Troubleshooting]]

CPU 使用率，就是除了空闲时间外的其他时间占总 CPU 时间的百分比。 =/proc/stat= 提供 CPU 和任务统计信息。

#+begin_verse
  单位 10ms

  cpu  100898 490 31309 2195013 10269 0 9757 0 0 0
  cpu0 13066 99 4666 273267 1044 0 4636 0 0 0
  cpu1 12794 48 4203 274005 1114 0 2619 0 0 0
  cpu2 12809 86 3815 274503 1218 0 1262 0 0 0
  cpu3 12629 33 3708 275046 993 0 576 0 0 0
  cpu4 12608 67 3700 274824 1158 0 220 0 0 0
  cpu5 12046 36 3833 274827 1385 0 182 0 0 0
  cpu6 12547 55 3753 274612 1438 0 147 0 0 0
  cpu7 12395 63 3629 273926 1915 0 114 0 0 0
#+end_verse
- ~man proc~ 查找 =/proc/stat= 查看每列所表示的含义
- user, nice, system, idle, iowait, irq(interrupts), softirq, steal, guest, guest_nice
  - nice: 代表低优先级用户态 CPU 时间，也就是进程的 nice 值被调整为 1-19 之间时的 CPU 时间； nice 可取值范围是 -20 到 19，数值越大，优先级反而越低
  - iowait: 代表等待 I/O 的 CPU 时间
  - irq: 代表处理硬中断的 CPU 时间
  - steal: 代表当系统运行在虚拟机中的时候，被其他虚拟机占用的 CPU 时间
  - guest: 运行虚拟机的 CPU 时间

* 计算公式
=/proc/stat= 统计的是开机以来的平均 CPU 使用率。为了计算 CPU 使用率，性能工具一般都会取间隔一段时间（比如 3 秒）的两次值，作差后，再计算出这段时间内的平均 CPU 使用率。
$$usage=1 - \frac{idle_t-idle_{t-1}}{total_t-total_{t-1}}$$

* 进程相关
=/proc/[pid]/stat=

* 总结
- 用户 CPU 和 Nice CPU 高，应着重排查进程的性能问题。
- 系统 CPU 高，应着重排查内核线程或者系统调用的性能问题。
- I/O 等待 CPU 高，应该着重排查系统存储是不是出现了 I/O 问题。
- 软中断和硬中断高，说明软中断或硬中断的处理程序占用了较多的 CPU，所以应该着重排查内核中的中断服务程序。
