:PROPERTIES:
:ID:       7475eede-346a-403e-9aac-91cab1e71a1f
:END:
#+title: Deadlock
#+filetags: :Concurrency:C++:

* Guidelines for Avoiding Deadlock
- Common Advice: Acquire locks in a *fixed order*
  - If you can't acquire them as a single operation with ~std::lock~, the next thing is to use [[*hierarchical_mutex]].
- Avoid nested locks
- *Avoid calling user supplied code while holding a lock*

* ~std::lock~
- ~std::lock~ can help you avoid deadlock in those cases where you need to acquire two or more locks together.
- it doesn't help if they're acquired *separately*. In that case, you have to rely on disciplines.
  #+begin_src c++
    friend void swap(X& lhs, X& rhs) {
      if (&lhs == &rhs)
        return;
      std::lock(lhs.m, rhs.m);
      std::lock_guard<std::mutex> lock_a(lhs.m, std::adopt_lock);
      std::lock_guard<std::mutex> lock_b(rhs.m, std::adopt_lock);
      swap(lhs.some_detail, rhs.some_detail);
    }
  #+end_src

** ~std::defer_lock~
- [Optimization]: You can optionally release a lock in a specific code branch if it's apparent that the lock is no longer required. This can be important for the performance.
#+begin_src c++
  std::unique_lock<std::mutex> lock_a(lhs.m, std::defer_lock);
  std::unique_lock<std::mutex> lock_a(rhs.m, std::defer_lock);
  std::lock(lock_a, lock_b); // Mutexes are locked here.
  swap(lhs.some_detail, rhs.some_detail);
#+end_src

** C++17 ~std::scoped_lock~
- ~std::scoped_lock guard(lhs.m, rhs.m);~

* hierarchical_mutex
When code tries to lock a mutex, it isn't permitted to lock that mutex if it already holds a lock from a lower layer. You can check this *at runtime* (at least not *timing-dependent*) by assigning layer numbers to each mutex and
keeping a record of which mutexes are locked by each thread. (Common Pattern)
- Implementation
#+begin_src c++
  #include <limits.h>
  #include <mutex>

  class hierarchical_mutex {
    std::mutex internal_mutex;
    unsigned long const hierarchy_value;
    unsigned long previous_hierarchy_value;
    static thread_local unsigned long this_thread_hierarchy_value;

    void check_for_hierarchy_violation() {
      if (this_thread_hierarchy_value <= hierarchy_value) {
        throw std::logic_error("mutex hierarchy violated");
      }
    }

    void update_hierarchy_value() {
      previous_hierarchy_value = this_thread_hierarchy_value;
      this_thread_hierarchy_value = hierarchy_value;
    }

  public:
    explicit hierarchical_mutex(unsigned long value)
        : hierarchy_value(value), previous_hierarchy_value(0) {}

    void lock() {
      check_for_hierarchy_violation();
      internal_mutex.lock();
      update_hierarchy_value();
    }

    void unlock() {
      if (this_thread_hierarchy_value != hierarchy_value)
        throw std::logic_error("mutex hierarchy violated");
      this_thread_hierarchy_value = previous_hierarchy_value;
      internal_mutex.unlock();
    }

    bool try_lock() {
      check_for_hierarchy_violation();
      if (!internal_mutex.try_lock())
        return false;
      update_hierarchy_value();
      return true;
    }
  };

  thread_local unsigned long
      hierarchical_mutex::this_thread_hierarchy_value(ULONG_MAX);
#+end_src
- Usage
#+begin_src c++
  hierarchical_mutex high_level_mutex(10000);
  hierarchical_mutex low_level_mutex(5000);
  hierarchical_mutex other_mutex(6000);
  int do_low_level_stuff();
  int low_level_func() {
    std::lock_guard<hierarchical_mutex> lk(low_level_mutex);
    return do_low_level_stuff();
  }
  void high_level_stuff(int some_param);
  void high_level_func() {
    std::lock_guard<hierarchical_mutex> lk(high_level_mutex); // OK
    high_level_stuff(low_level_func());
  }
  void thread_a() { high_level_func(); }
  void do_other_stuff();
  void other_stuff() {
    high_level_func();
    do_other_stuff();
  }
  void thread_b() {
    std::lock_guard<hierarchical_mutex> lk(
        other_mutex); // violating the hierarchy
    other_stuff();
  }
#+end_src

* Transferring Mutex Ownership
Usage: when the lock isn't returned directly but is a data member of a gateway class used to ensure correctly locked access to some protected data.
- When you're finished, you destroy the gateway object, which releases the lock.
#+begin_src c++
  std::unique_lock<std::mutex> get_lock() {
    extern std::mutex some_mutex;
    std::unique_lock<std::mutex> lk(some_mutex);
    prepare_data();
    return lk;
  }
#+end_src
