:PROPERTIES
:ID:       09ea9033-4067-4a2f-b442-b7da136fa5be
:END:
#+title: Financial Terminology
#+filetags: :Trading:

* Terminologies
- Ticker *Symbol* :: AAPL for Apple, TSLA for Tesla
- Stock :: An asset that represents ownership in a company. A claim on part of a corportation's
  assets and earnings. There are two main types, common and preferred.
- Share :: A single share represents partial ownership of a company relative to the total number
  of shares in existence.
- Common Stock :: One main type of stock; entitles the owner to receive dividends and to vote at
  shareholder meetings.
- Preferred Stock :: The other main type of stock; generally does not entail voting rights, but
  entitles the owner to a higher claim on the assets and earnings of a company.
- Dividend :: A partial distribution of a company's profits to shareholders.
- Capital Gains :: Profits that result from the sale of an asset at a price higher than the
  purchase price.
- Security :: A tradable financial asset.
- Debt Security :: Money that is owed and must be repaid, like government or corporate bonds,
  or certificates of deposit. Also called fixed-income securities.
- Derivative Security :: A financial instrument whereby its value is derived from other assets.
- Equity :: The value of an owned asset minus the amount of all debts on that asset.
- Equity Security :: A security that represents fractional ownership in an entity, such as stock.
- Option Contract :: A contract which gives the buyer the right, but not the obligation, to buy
  or sell an underlying asset at a specified price on or by a specified date
- Futures Contract :: A contract that obligates the buyer to buy or the seller to sell an asset
  at a predetermined price at a specified time in the future
- American Depository Receipts(ADR) :: Foreign stocks are sometimes allowed to trade on a local
  stock exchange via an indirect method such as American Depository Receipts (ADR).
  These are instruments that represent the original stock in a different market.

* Market
:PROPERTIES:
:ID:       968a4e81-2072-4fe4-b713-2ebd0e7c8487
:END:
- Pre-market :: Market participants often use pre-market session to gauge the strength and direction of the market.
- Post-market :: are often used by traders who want to trade on corporate announcements made after market closes, or for brokers to make whole of an incomplete client order.

* Market Data
:PROPERTIES:
:ID:       93cd33e9-64f3-4f7d-b132-5b0c11e49cd3
:END:
- Volume :: Volume refers to the number of shares, contracts, or units of a particular asset that are traded within a specific period of time.
- Tick Data :: Tick data is sometimes referred to as heterogeneous data, since it is not sampled
  at regular time intervals, whereas Minute-level or End-of-Day data is called homogeneous.

* 中文名词
- 股权工具 (Equity) :: 股权工具是其持有者按份额拥有的对企业净收益（扣除费用和税收后的收入）和资产的剩余求偿权。
- 一级市场 (Primary Market) :: 是筹集资金的公司或者政府机构将新发行的债券或者股票等出售给最初购买者的金融市场。
- 投资银行 (Investment Bank) :: 在一级市场协助实施首次销售的金融机构，它为公司证券提供了一个承诺的价格，继而向公众发售。
- [[id:4132e7b9-067d-4f97-b937-7c61dc744ad2][二级市场]] (Secondary Market) :: 是已经发行的证券进行转售交易的金融市场。
- 经纪人 (Brokers) :: 是投资者的代理人，负责实现证券买卖双方的匹配。
- 交易商 (Dealers) :: 是通过按照报价买卖证券的活动将证券的买卖双方联系起来。
- 场外交易市场 (OTC) :: over-the-counter market
- 可转让定期存单 :: Negotiable Certificates of Deposit, CD
- 货币市场 (Monkey Market) :: 是短期债务工具进行交易的金融市场。
- 资本市场 (Capital Market) :: 是长期债务工具和股权工具进行交易的金融市场。

** 货币市场名词
- 优惠利率 (Prime Rate) :: 企业银行贷款的基准利率，标识企业从银行借款的成本指标。
- 联邦基金利率 (Federal Funds Rate) :: 联邦基金市场中隔夜贷款的利率，标识银行间借款成本和货币政策立场的敏感指标。
- [[id:167c14ef-51ed-4a7c-9cb6-b6906fee366d][国库券]]利率 (Treasure Bill Rate) :: 它是美国国库券的利率，标识基本利率活动的指标。
- 伦敦同业拆放利率 (Libor Rate) :: 英国银行协会给出的伦敦市场中美元存款的银行间平均利率。
- 商业票据 (Commercial Paper) :: 它是大型银行和著名企业发行的短期债务工具。
- 回购协议 (Repurchase Agreement, repos) :: 是一种有效的短期贷款（短于2周），回购协议是借钱者将国库券作为抵押品。
