:PROPERTIES:
:ID:       68e3c654-3919-4f7b-8a60-04f011ed3e72
:END:
#+TITLE: Python Profiling

- tags :: [[id:e1ded36e-459f-4ef3-b971-dc0ead283f5a][High Performance Python]], [[id:65ffd8bc-fcb7-4875-9b70-69b0f24979cb][Profiling]], [[id:87849bbc-e437-41aa-b44d-db9ffa63e633][Python]]

* Practical Points
- Disable Turbo Boost in the BIOS.
- Disable the operating system's ability to override the SpeedStep(in BIOS).
- Use only AC power (never battery power).
- Disable background tools like backups and Dropbox while running experiments.
- Run the experiments many times to obtain a stable measurement.
- Possibly drop to run level 1 (Unix) so that no other tasks are running.
- Reboot and rerun the experiments to double-confirm the results.
- Unit testing a complicated section of code that generates a large numerical output may be difficult.
  Do not be afraid to output a text file of results to run through ~diff~ or to use a pickled object.

* Tools
** 基础常用工具
*** ~/usr/bin/time~
   - Using ~--verbose~ flag to get more details.
   - Most useful indicator is ~Major (requiring IO) page faults~, as it indicates cache misses.
*** ~timefn~ decorator
   #+BEGIN_SRC python
     def timefn(fn):
         @wraps(fn)
         def measure_time(*args, **kwargs):
             t1 = time.time()
             result = fn(*args, **kwargs)
             t2 = time.time()
             print(f"@timefn: {fn.__name__} took {t2 - t1} seconds")
             return result

         return measure_time
   #+END_SRC
*** bulit-in ~timeit~ module
   - [[https://docs.python.org/3/library/timeit.html][Documentation]]
   - The ~timeit~ module temporarily disables the garbage collector.
   - More useful approach: IPython magic ~%timeit~
*** CProfile
   #+BEGIN_SRC sh
     python -m cProfile -s cumulative test.py
     python -m cProfile -o profile.stats test.py
   #+END_SRC
   #+BEGIN_SRC python
     import pstats
     p = pstats.Stats("profile.stats")
     p.sort_stats("cumulative")
     p.print_stats()
     p.print_callers()
     p.print_callees()
   #+END_SRC
*** ~line_profiler~
   1. ~pip install line_profiler~
   1. Use ~@profile~ to mark the chosen function
   1. ~kernprof -l -v test.py~
   1. See report: ~python -m line_profiler test.py.lprof~

**** Object Interface
     #+BEGIN_SRC python
       from line_profiler import LineProfiler

       lp = LineProfiler(some_func)
       lp.run("some_func(args)")
       lp.print_stats()
     #+END_SRC
   - ~snakeviz~ for visualization


** ~ipython~ magic
- ~%memit~: ~%load_ext memory_profiler~
- ~%%timeit~: ~%%timeit array1, array2 = np.random.random((2, 100, 100))~

** GPU Profiling
- ~nvidia-smi~
- ~gpustat~

** PyTorch Profiling
~python -m torch.utils.bottleneck test.py~

** For Web Servers
- ~dowser~
- ~dozer~

* 技巧
** No-op @profile
  Add it to the start of our module while unit testing
  #+BEGIN_SRC python
    if 'line_profiler' not in dir() and 'profile' not in dir():
    def profile(func):
        return func
  #+END_SRC
