:PROPERTIES:
:ID:       e391bae0-8c6c-492f-a66c-f4629f61e972
:END:
#+TITLE: Scikit-Learn
#+filetags: :ML:
- tags :: [[id:c5c869b4-7869-42d8-9c46-1487715b8de6][Machine Learning Development]]

* Design
** Consistency
*** Estimators
Any object that can estimate some parameters based on a dataset
is called an *estimator*. (e.g. an /imputer/)
- The estimation itself is performed by the ~fit()~ method
  - takes only datasets as parameters
- Any other parameters are hyperparameter, generally set via a constructor parameter.

*** Transformers
Some estimators can transform a dataset; they are called /transformers/.
- ~transformed = estimator.transform(input_dataset)~
- This transformation generally relies on the learned parameters.(~fit()~ results)
- Convenience method ~fit_transform()~

*** Predictors
Some estimators are capable of making predictions given a dataset; they are called predictors.
- ~predict()~ takes a dataset of new instances and returns a dataset of corresponding predictions.
- ~score()~ measures the quality of the predictions given a test set.

** Inspection
- All the estimator's hyperparameters are accessible directly via *public instance variables*
- All the estimator's learned parameters are accessible via *public instance variables with an underscore suffix*

** Nonproliferation of Classes
Datasets are represented as NumPy arrays or SciPy sparse matrices,
instead of homemade classes. Hyperparameters are just regular Python
strings or numbers.

** Composition
It is easy to create a Pipeline estimator from an arbitrary sequence of
transformers followed by a final estimator.
