:PROPERTIES:
:ID:       02e09a1c-a8c8-4102-a444-0498e8dfb993
:END:
#+title: ~std::initializer_list~
#+filetags: :C++:

* Initialization Ways
  #+begin_src cpp
    Widget w1; // default constructor
    Widget w2 = w1; //calls copy constructor
    w3 = w2; // calls copy operator=
    int x(0); // in parentheses
    int y = 0;
    int z{0}; // in braces
    int z = {0}; // same as the braces-only version
    std::vector<int> v{1, 3, 5}; // in braces. Uniform initialization

    class Widget {
     public:
      Widget(int i1, int i2);
      Widget(std::initializer_list<int int> i);
     private:
      int x{0}; // uniform initialization for member's default value
    };

    Widget w1(5, 4); // calls Widget(int i1, int i2)
    Widget w2{5, 4}; // calls Widget(std::initializer_list<int int> i)
  #+end_src
- During constructor overload resolution, braced initializers are matched to
std::initializer_list parameters if at all possible, even if other constructors
offer seemingly better matches.

* ~std::vector~ Case
  #+begin_src cpp
    // use non-std::initializer_list ctor: create 10-element std::vector
    std::vector<int> v1(10, 20);

    // use std::initializer_list: create 2-element std::vector
    std::vector<int> v2{10, 20};
  #+end_src
- As a class author, you should add ~std::initializer_list~ overloads only with great deliberation.
- As a class client, you must choose carefully between parentheses and braces.

* Uniform Initialization
** Advantages
- Prevents *implicit* narrowing conversions
- Immune to C++'s most vexing parse. ~Widget w3();~ could be parsed as declaring a function.

** Drawbacks
- auto-deduced-a-std::initializer_list problem, see [[id:c19b4842-be7b-4a29-a85b-462cbad2c6c1][~auto~]]
  - As a result, the more you like auto, the less enthusiastic you’re likely to be about braced initialization.
