:PROPERTIES:
:ID:       597c7ffb-ebaa-4c37-b5e7-ee7fca486d05
:END:
#+TITLE: ~std::initializer_list~

- tags :: [[id:f670bcb9-d35a-449e-9b40-682471392631][Modern C++]], [[id:f89b0a9e-d3b9-45eb-ac4b-044b4a0cd709][~auto~]]


* Initialization Ways
  #+begin_src cpp
    Widget w1; // default constructor
    Widget w2 = w1; //calls copy constructor
    w3 = w2; // calls copy operator=
    int x(0); // in parentheses
    int y = 0;
    int z{0}; // in braces
    int z = {0}; // same as the braces-only version
    std::vector<int> v{1, 3, 5}; // in braces. Uniform initialization

    class Widget {
     public:
      Widget(int i1, int i2);
      Widget(std::initializer_list<int int> i);
     private:
      int x{0}; // uniform initialization for member's default value
    };

    Widget w1(5, 4); // calls Widget(int i1, int i2)
    Widget w2{5, 4}; // calls Widget(std::initializer_list<int int> i)
  #+end_src
- During constructor overload resolution, braced initializers are matched to
std::initializer_list parameters if at all possible, even if other constructors
offer seemingly better matches.

* ~std::vector~ Case
  #+begin_src cpp
    // use non-std::initializer_list ctor: create 10-element std::vector
    std::vector<int> v1(10, 20);

    // use std::initializer_list: create 2-element std::vector
    std::vector<int> v2{10, 20};
  #+end_src
- As a class author, you should add ~std::initializer_list~ overloads only with great deliberation.
- As a class client, you must choose carefully between parentheses and braces.

* Uniform Initialization
** Advantages
- Prevents *implicit* narrowing conversions
- Immune to C++'s most vexing parse. ~Widget w3();~ could be parsed as declaring a function.

** Drawbacks
- auto-deduced-a-std::initializer_list problem, see [[id:f89b0a9e-d3b9-45eb-ac4b-044b4a0cd709][~auto~]]
  - As a result, the more you like auto, the less enthusiastic you’re likely to be about braced initialization.
